- src/app/layout.js
> signed commit

- .github/workflows/deploy-to-s3.yaml
- src/app/views/clinic_summary/ClinicSummary.test.js
- src/app/views/clinic_summary/ClinicSummaryPage.jsx
- src/app/views/clinic_summary/ClinicSummaryTable.jsx
Minor changes to clinic summary screen.
---
> added minor changes to clinic summary screen

- package-lock.json
- src/app/page.jsx
- src/app/views/clinic_summary/ClinicSummary.js
- src/app/views/clinic_summary/ClinicSummary.test.js
- src/app/views/clinic_summary/ClinicSummaryPage.jsx
- src/app/views/clinic_summary/ClinicSummaryTable.jsx
- src/app/views/clinic_summary/helper.js
https://nhsd-jira.digital.nhs.uk/browse/GAL-351
This ticket does small amounts of rework to render the data from the completed backend correctly 
---
> Gal 351/clinic summary backend

- package-lock.json
- src/app/models/invitation_planning/NationalForecastUptake.js
- src/app/page.jsx
- src/app/views/invitation_planning/InvitationPlanning.js
- src/app/views/invitation_planning/InvitationPlanningPage.jsx
- src/app/views/invitation_planning/NationalForecastUptakeTable.jsx
- src/app/views/invitation_planning/QuintileTargetTable.jsx
- src/app/views/invitation_planning/helper.js
https://nhsd-jira.digital.nhs.uk/browse/GAL-209
https://nhsd-jira.digital.nhs.uk/browse/GAL-352
Adding put and get calls to backend
---
> Gal 352/update frontend api fetch

- src/app/views/clinic_information/ClinicInformation.js
- src/app/views/clinic_information/ClinicInformationPage.jsx
- src/app/views/clinic_information/RecentInvitationHistory.jsx
- src/app/views/clinic_summary/ClinicSummary.js
- src/app/views/invitation_planning/InvitationPlanning.js
Resolution for bug fix to have the "View all previous invitations" link displayed or hidden depending on the values on Recent Invitation History" Table
- [x ] I have followed the code style of the project
---
> gal-557# Bug Fix to have View previous invitations link display and hide

- package-lock.json
- package.json
> upgrade node

- src/app/page.jsx
- src/app/views/clinic_summary/ClinicSummary.js
- src/app/views/clinic_summary/ClinicSummaryTable.jsx
clinics listed in the 'Clinic List' section are now ordered from oldest to newest invitation sent date as per Figma screens
Bug: https://nhsd-jira.digital.nhs.uk/browse/GAL-471
---
> Gal 471/sort preinvite data

- README.md
- src/app/views/invitation_planning/InvitationPlanning.js
Resolved the duplicate axios import
axios was being imported twice which was causing node to crash on startup
---
> AC - removed duplicate axios issue

- src/app/page.jsx
- src/app/styles/css/sass.css
- src/app/views/clinic_information/ClinicInformationPage.jsx
- src/app/views/invitation_summary/Actions.jsx
- src/app/views/invitation_summary/CheckDetailsBanner.jsx
- src/app/views/invitation_summary/ClinicInfo.jsx
- src/app/views/invitation_summary/ConfirmationBanner.jsx
- src/app/views/invitation_summary/ErrorBanner.jsx
- src/app/views/invitation_summary/InvitationSummary.js
- src/app/views/invitation_summary/InvitationSummary.test.js
- src/app/views/invitation_summary/InvitationSummaryPage.jsx
- src/app/views/invitation_summary/SummaryListFirst.jsx
- src/app/views/invitation_summary/SummaryListSecond.jsx
Created FrontEnd Components for the Invitation Summary Page with functionality for different scenarios.
---
> Gal 488/invitation summary page

- src/app/page.jsx
- src/app/views/start_page/Start.js
- src/app/views/start_page/StartPage.jsx
Added Splash Page for the Demo.
---
> added Start Page for Demo

- README.md
- package.json
Updated the npm start command to work with elastic beanstalk
Elastic Beanstalk is how we will be deploying this into aws. When it deploys it runs the start command and without adding the build command it fails. It also redirects traffic from 80 to 8080 by using an environmental variable.
---
> AC - updated the npm start script to work with beanstalk

- gulpfile.js
- src/app/components/pagination.js
- src/app/views/clinic_information/ClinicInformation.js
- src/app/views/clinic_information/ClinicInformationPage.jsx
- src/app/views/clinic_information/LsoaTable.jsx
- src/app/views/clinic_information/config/milesOptions.json
- src/app/views/invitation_planning/InvitationPlanning.js
> Gal 606/branch 2

- src/app/views/clinic_summary/ClinicSummaryTable.jsx
Removed hyperlink to prevent navigation to a clinic where availability is 0.
---
> Removed hyperlink when availibity is 0 for a clinic.

- src/app/views/clinic_information/ClinicInformation.js
- src/app/views/clinic_summary/ClinicSummary.js
- src/app/views/invitation_planning/InvitationPlanning.js
- src/app/views/invitation_summary/InvitationSummary.js
Added URL environment variables for API ID
As the API ID will change every time the api gateway is re-deployed this should stop the manual change currently needed.
---
> AC - added URL references

- src/app/components/Footer.jsx
- src/app/components/Header.jsx
- src/app/components/NavMenu.jsx
- src/app/components/Pagination.js
- src/app/components/content.jsx
- src/app/layout.jsx
- src/app/page.jsx
- src/app/styles/css/sass.css
- src/app/views/clinic_information/ClinicInformation.test.js
- src/app/views/clinic_information/ErrorBannerDetail.jsx
- src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
- src/app/views/invitation_planning/ErrorInvitations.jsx
- src/app/views/invitation_planning/InvitationPlanningPage.jsx
- src/app/views/invitation_planning/NationalForecastUptakeTable.jsx
- src/app/views/invitation_planning/QuintileTargetTable.jsx
- src/app/views/invitation_summary/Actions.jsx
- src/app/views/invitation_summary/ErrorBanner.jsx
- src/app/views/invitation_summary/InvitationSummaryPage.jsx
- src/app/views/invitation_summary/SummaryListFirst.jsx
- src/app/views/invitation_summary/SummaryListSecond.jsx
- src/app/views/start_page/StartPage.jsx
When running static analysis it complains about using class instead of the react preferance for classname.
This should elimiate complains from unit tests and static code analysis
---
> AC - replaced references to class with classname

- src/app/views/clinic_information/ClinicInformation.js
https://nhsd-jira.digital.nhs.uk/browse/GAL-570
---
> GAL-570 fix for postcode prev_state variable

- src/app/views/clinic_information/ClinicInformation.js
- src/app/views/clinic_information/LsoaTable.jsx
https://nhsd-jira.digital.nhs.uk/browse/GAL-465
Also, added a change for Targetpercentage as this field has been moved to Phlebetomy site table from Invitation Parameters Table.
---
>  Pagination changes for consistent LSOA-range, currentPage & pagesize

- src/app/components/Pagination.js
hotfix for dots pagination as part of GAL-795
---
> hotfix for dots

- src/app/components/Header.jsx
- src/app/page.jsx
- src/app/styles/css/sass.css
- src/app/views/invitation_planning/ErrorInvitations.jsx
- src/app/views/invitation_planning/Errorinvitations.test.js
- src/app/views/invitation_planning/InvitationPlanning.js
- src/app/views/invitation_planning/InvitationPlanningPage.jsx
- src/app/views/invitation_planning/InvitationPlanningPage.test.js
- src/app/views/invitation_planning/NationalForecastUptakeTable.jsx
- src/app/views/invitation_planning/NationalForecastUptakeTable.test.js
- src/app/views/invitation_planning/QuintileTargetTable.jsx
- src/app/views/invitation_planning/QuintileTargetTable.test.js
Addressed the Accessibility issues on the Invitation Planning Page
---
> Gal 777/accessibility invitation variables

- jest.config.js
- package.json
- scripts/reports/perform-static-analysis.sh
- src/app/components/Header.jsx
- src/app/page.jsx
- src/app/styles/css/sass.css
- src/app/views/clinic_information/ClinicInformation.js
- src/app/views/invitation_summary/Actions.jsx
- src/app/views/invitation_summary/CheckDetailsBanner.jsx
- src/app/views/invitation_summary/CheckDetailsBanner.test.js
- src/app/views/invitation_summary/ClinicInfo.jsx
- src/app/views/invitation_summary/ClinicInfo.test.js
- src/app/views/invitation_summary/ConfirmationBanner.jsx
- src/app/views/invitation_summary/ConfirmationBanner.test.js
- src/app/views/invitation_summary/InvitationSummary.js
- src/app/views/invitation_summary/InvitationSummaryPage.jsx
- src/app/views/invitation_summary/InvitationSummaryPage.test.js
- src/app/views/invitation_summary/SummaryListFirst.jsx
- src/app/views/invitation_summary/SummaryListFirst.test.js
- src/app/views/invitation_summary/SummaryListSecond.jsx
- src/app/views/invitation_summary/SummaryListSecond.test.js
- src/app/views/start_page/Start.js
Addressed the accessibility issue and made improvements. Also fixed the Target number of appointments to fill value not updating when changing the clinic on ClinicInformation screen.
---
> Gal 775 & 776 /accessibility invitation summary

- src/app/styles/css/sass.css
Fix for main in sass.css - missing curly brace.
---
> Enclosing curly brace  missing in .custom-pointer class.

- src/app/views/clinic_information/ClinicInformation.js
Included in GAL-465
Implement change for resetting checkbox selection in LSOA table after returning to Clinic Invitations screen. 
---
> Resetting select checkbox

- src/app/views/clinic_information/ClinicInformation.js
- src/app/views/clinic_information/ClinicInformationPage.jsx
- src/app/views/clinic_information/LsoaTable.jsx
- src/app/views/clinic_information/LsoaTable.test.js
https://nhsd-jira.digital.nhs.uk/browse/GAL-815
As per requirements, Forecast Uptake of each LSOA is the product of Moderator values of that value and National Forecast Uptake. 
---
> ForecastUptake change

- src/app/views/clinic_information/ClinicInformation.js
moving LSOA-In-Range to context variables
---
> moving LSOA-In-Range to context variables

- src/app/views/clinic_information/ClinicInformation.js
CalculateNumberToInvite Lambda was not generating correct results
---
> Cal-number-to-invite

- src/app/page.jsx
- src/app/views/privacy_confirmation/PrivacyConfirmation.js
- src/app/views/privacy_confirmation/PrivacyConfirmation.test.js
- src/app/views/privacy_confirmation/PrivacyConfirmationPage.jsx
- src/app/views/referrals_summary/ReferralsSummary.js
Added privacy confirmation screen.
---
> Gal 381/privacy page

- src/app/views/clinic_information/LsoaTable.jsx
- src/app/views/clinic_information/LsoaTable.test.js
https://nhsd-jira.digital.nhs.uk/browse/GAL-876
---
> Overalluptake% change

- src/app/views/clinic_information/LsoaTable.jsx
- src/app/views/clinic_information/LsoaTable.test.js
https://nhsd-jira.digital.nhs.uk/browse/GAL-897
Fixed by Aviraj. Submitting PR on his behalf
---
> forecastUptake value should not exceed 100

- src/app/styles/css/sass.css
- src/app/views/invitation_summary/SummaryListFirst.jsx
- src/app/views/invitation_summary/SummaryListSecond.jsx
https://nhsd-jira.digital.nhs.uk/browse/GAL-891
https://nhsd-jira.digital.nhs.uk/browse/GAL-892
---
> Aviraj Tickets: 891 & 892

- src/app/views/clinic_information/ClinicInformation.js
https://nhsd-jira.digital.nhs.uk/browse/GAL-888
---
> GAL-888 Issue 1 fix

- package.json
- src/app/api/auth/[...nextauth]/route.ts
- src/app/components/NavMenu.jsx
- src/app/context/AutoSignOutProvider.jsx
- src/app/signin/page.jsx
- src/app/views/invitation_planning/ErrorInvitations.jsx
- src/app/views/invitation_planning/NationalForecastUptakeTable.jsx
- src/app/views/invitation_planning/QuintileTargetTable.jsx
- src/app/views/invitation_planning/QuintileTargetTable.test.js
- src/app/views/invitation_summary/SummaryListFirst.jsx
- src/app/views/invitation_summary/SummaryListFirst.test.js
- src/app/views/invitation_summary/SummaryListSecond.jsx
- src/app/views/invitation_summary/SummaryListSecond.test.js
- src/app/views/privacy_confirmation/PrivacyConfirmation.test.js
- src/app/views/privacy_confirmation/PrivacyConfirmationPage.jsx
- tsconfig.json
Fix for getting the FrontEnd stable on ElasticBeanstalk. Added deployment stage steps for nextauth.
---
> hotfix# typescript build

- src/app/components/Header.jsx
- src/app/context/AutoSignOutProvider.jsx
- src/app/layout.jsx
- src/app/page.jsx
- src/app/signin/page.jsx
- src/app/views/clinic_information/ClinicInformationPage.jsx
- src/app/views/clinic_summary/ClinicSummary.js
- src/app/views/clinic_summary/ClinicSummaryPage.jsx
- src/app/views/invitation_planning/InvitationPlanning.js
- src/app/views/invitation_planning/InvitationPlanningPage.jsx
- src/app/views/invitation_planning/InvitationPlanningPage.test.js
- src/app/views/invitation_summary/InvitationSummaryPage.jsx
- src/app/views/invitation_summary/InvitationSummaryPage.test.js
- src/app/views/logged_out/LoggedOut.jsx
- src/app/views/logged_out/LoggedOut.test.jsx
- src/app/views/privacy_confirmation/PrivacyConfirmation.js
- src/app/views/privacy_confirmation/PrivacyConfirmation.test.js
- src/app/views/privacy_confirmation/PrivacyConfirmationPage.jsx
refer to: [Original PR](https://github.com/NHSDigital/Galleri-Frontend/pull/110)
> Inactivity timer branch with verified commits

- src/app/views/privacy_confirmation/PrivacyConfirmationPage.jsx
Ensuring the redirection happens fine and get an authorisation code back as url query parameter after authenticating successfully with CIS2. Extract the code from the url and clear the query params.
---
> Gal 704/cis2 redirect url auth code

- src/app/api/auth/[...nextauth]/route.ts
> GAL-705 Added post CIS2 token request with the authorisation code

- src/app/layout.jsx
- src/app/views/logged_out/LoggedOut.jsx
> Match design for inactivity timeout and conditional rendering of minute

- src/app/api/auth/[...nextauth]/route.ts
- src/app/views/privacy_confirmation/PrivacyConfirmationPage.jsx
Added Userinfo option in cis2 provider config that exchanges the token for user info and persists it on session object.
---
> gal-706/added userinfo options in cis2 provider config

- .github/workflows/check-file-format.yaml
- .github/workflows/check-markdown-format.yaml
- .github/workflows/check-terraform-format.yaml
- .github/workflows/cicd-pipeline.yaml
- .github/workflows/cloc-repository.yaml
- .github/workflows/deploy-to-s3.yaml
- .github/workflows/scan-dependencies.yaml
- .github/workflows/scan-secrets.yaml
- next.config.js
updated node versions
This should sort out the problems with node versions
---
> updated node version

- .github/actions/perform-static-analysis/action.yaml
- .github/workflows/manual-deploy.yaml
Installing node 20 on the github runner
Sonarcloud has depricated node 18 for some reason, possibly a bug on their end but unless they fix it we need to adapt.
---
> testing installing node 20

- .github/workflows/cicd-2-publish.yaml
Fixed bad syntax in workflow file
The bad syntax was erroring when workflow attempts to run upon merging into main branch.
---
> Fix for pipeline not running upon merge into main

- src/app/helper/helperMethods.js
- src/app/views/clinic_information/ClinicInformation.js
> Fixed integration issues

- src/app/api/auth/[...nextauth]/route.ts
Hot pic to add the missing env variable interpolation on the api-endpoint for authenticator lambda
---
> HOTFIX# added missing env variable interpolation on the api_endpoint

- src/app/api/auth/[...nextauth]/route.ts
Added scope parameter Max_age during authentication with CIS2
---
> Hotfix/added max_age parameter for auth

- src/app/views/clinic_summary/ClinicSummary.js
- src/app/views/clinic_summary/ClinicSummaryPage.jsx
- src/app/views/clinic_summary/ClinicSummaryTable.jsx
> Added error message if no clinincs available

- src/app/api/auth/[...nextauth]/route.ts
- src/app/views/invitation_planning/InvitationPlanningPage.jsx
- src/app/views/invitation_planning/InvitationPlanningPage.test.js
- src/app/views/privacy_confirmation/PrivacyConfirmationPage.jsx
As pointed out in CIS2 SA call, removed the email scope when authenticating with CIS2 as it's not required. Also protected the path to Invitation Planning page.
---
> hotfix# Removed Email scope from Authentication
